name: build
on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '7.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@main

      - name: setup dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/azure-devops-compliance/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PAT }}

      - name: dotnet build
        run: dotnet build Functions -c release

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout main
  #       uses: actions/checkout@main

  #     - name: sestup dotnet ${{ env.DOTNET_VERSION }}
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: ${{ env.DOTNET_VERSION }}
  #         source-url: https://nuget.pkg.github.com/azure-devops-compliance/index.json
  #       env:
  #         NUGET_AUTH_TOKEN: ${{ secrets.PAT }}
  #     - name: dotnet test
  #       run: dotnet test -c release  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  #       env:
  #         TOKEN: ${{secrets.AZURE_DEVOPS_TOKEN}}
  #         AzureWebJobsStorage: ${{secrets.AzureWebJobsStorage}}
  #     - uses: codecov/codecov-action@v1
  
  # mutation-test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout main
  #       uses: actions/checkout@main
  
  #     - name: setup dotnet ${{ env.DOTNET_VERSION }} 
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: ${{ env.DOTNET_VERSION }}
  #         source-url: https://nuget.pkg.github.com/azure-devops-compliance/index.json
  #       env:
  #         NUGET_AUTH_TOKEN: ${{ secrets.PAT }}

  #     - name: stryker
  #       run: |
  #         dotnet tool install -g dotnet-stryker
  #         dotnet stryker -tp "['Functions.Tests/Functions.Tests.csproj']" -im "['ConfigureAwait']" --reporters "['dashboard']" --dashboard-project github.com/azure-devops-compliance/azure-functions/main
  #       env:
  #         STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_TOKEN }}